version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    networks:
      - blackcoffer_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - blackcoffer_network

networks:
  blackcoffer_network:
    driver: bridge
